// <auto-generated />
using System;
using BA.DietTrackApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BA.DietTrackApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Calori")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FoodTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodTypeId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calori = 114m,
                            FName = "Armut-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Calori = 98m,
                            FName = "Ayva-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Calori = 44m,
                            FName = "Beyaz dut-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Calori = 163m,
                            FName = "Beyaz üzüm-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Calori = 68m,
                            FName = "Böğürtlen-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Calori = 46m,
                            FName = "Çilek-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Calori = 52m,
                            FName = "Elma-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Calori = 9m,
                            FName = "Erik-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Calori = 52m,
                            FName = "Frambuaz-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Calori = 150m,
                            FName = "Greyfurt-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Calori = 48m,
                            FName = "İncir-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Calori = 343m,
                            FName = "Karadut-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Calori = 105m,
                            FName = "Karpuz-1 dilim (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Calori = 76m,
                            FName = "Kavun-1 dilim (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            Calori = 14m,
                            FName = "Kayısı-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            Calori = 4m,
                            FName = "Kiraz-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            Calori = 61m,
                            FName = "Kivi-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            Calori = 49m,
                            FName = "Kuşburnu-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            Calori = 43m,
                            FName = "Limon-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            Calori = 66m,
                            FName = "Mandalina-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            Calori = 151m,
                            FName = "Muz-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            Calori = 101m,
                            FName = "Portakal-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            Calori = 160m,
                            FName = "Siyah üzüm-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            Calori = 78m,
                            FName = "Şeftali-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 25,
                            Calori = 3m,
                            FName = "Vişne-1 adet (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            Calori = 44m,
                            FName = "Yaban mersini-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            Calori = 159m,
                            FName = "Yeşil üzüm-1 kase (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            Calori = 40m,
                            FName = "Ananas-1 dilim (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 29,
                            Calori = 224m,
                            FName = "Avokado-1 adet",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            Calori = 97m,
                            FName = "Çarkıfelek-1 adet",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            Calori = 354m,
                            FName = "Hindistan cevizi-1 adet",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            Calori = 26m,
                            FName = "Hurma-1 adet",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 33,
                            Calori = 59m,
                            FName = "Mango-1 adet",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 34,
                            Calori = 42m,
                            FName = "Papaya-1 adet",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            Calori = 11m,
                            FName = "Pomelo-1 dilim (orta)",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 36,
                            Calori = 30m,
                            FName = "Yıldız meyvesi-1 adet",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 37,
                            Calori = 336m,
                            FName = "Dut-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 38,
                            Calori = 346m,
                            FName = "Goji berry-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 39,
                            Calori = 249m,
                            FName = "Kuru incir-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 40,
                            Calori = 241m,
                            FName = "Kuru kayısı-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 41,
                            Calori = 299m,
                            FName = "Kuru üzüm-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            Calori = 302m,
                            FName = "Kuru yaban mersini-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 43,
                            Calori = 335m,
                            FName = "Kurutulmuş portakal-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 44,
                            Calori = 283m,
                            FName = "Kuş üzümü-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 45,
                            Calori = 525m,
                            FName = "Muz kurusu-100 gram",
                            FoodTypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            Calori = 42m,
                            FName = "Akdeniz yeşillikleri-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 47,
                            Calori = 72m,
                            FName = "Bakla-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 48,
                            Calori = 33m,
                            FName = "Bal kabağı-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 49,
                            Calori = 36m,
                            FName = "Bamya-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 50,
                            Calori = 25m,
                            FName = "Beyaz lahana-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 51,
                            Calori = 84m,
                            FName = "Bezelye-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 52,
                            Calori = 22m,
                            FName = "Biber-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 53,
                            Calori = 34m,
                            FName = "Brokoli-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 54,
                            Calori = 63m,
                            FName = "Brüksel lahanası-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 55,
                            Calori = 40m,
                            FName = "Deniz börülcesi-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 56,
                            Calori = 42m,
                            FName = "Dere otu-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 57,
                            Calori = 22m,
                            FName = "Domates-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 58,
                            Calori = 53m,
                            FName = "Enginar-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 59,
                            Calori = 13m,
                            FName = "Göbek salata-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 60,
                            Calori = 45m,
                            FName = "Havuç-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 61,
                            Calori = 26m,
                            FName = "Ispanak-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 62,
                            Calori = 26m,
                            FName = "Kabak-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 63,
                            Calori = 45m,
                            FName = "Kara lahana-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 64,
                            Calori = 27m,
                            FName = "Karnıbahar-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 65,
                            Calori = 40m,
                            FName = "Kereviz-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 66,
                            Calori = 31m,
                            FName = "Kırmızı lahana-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 67,
                            Calori = 20m,
                            FName = "Kıvırcık salata-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 68,
                            Calori = 26m,
                            FName = "Körpe ıspanak-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 69,
                            Calori = 26m,
                            FName = "Kuşkonmaz-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 70,
                            Calori = 42m,
                            FName = "Kuzu kulağı-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 71,
                            Calori = 56m,
                            FName = "Limon-1 adet",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 72,
                            Calori = 22m,
                            FName = "Madımak-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 73,
                            Calori = 28m,
                            FName = "Mantar-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 74,
                            Calori = 14m,
                            FName = "Marul-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 75,
                            Calori = 14m,
                            FName = "Maskulin salata-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 76,
                            Calori = 44m,
                            FName = "Maydonoz-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 77,
                            Calori = 91m,
                            FName = "Mısır-1 adet",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 78,
                            Calori = 42m,
                            FName = "Pancar-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 79,
                            Calori = 76m,
                            FName = "Patates-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 80,
                            Calori = 25m,
                            FName = "Patlıcan-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 81,
                            Calori = 33m,
                            FName = "Pazı-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 82,
                            Calori = 52m,
                            FName = "Pırasa-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 83,
                            Calori = 33m,
                            FName = "Roka-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 84,
                            Calori = 15m,
                            FName = "Salatalık-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 85,
                            Calori = 123m,
                            FName = "Sarımsak-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 86,
                            Calori = 32m,
                            FName = "Semiz otu-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 87,
                            Calori = 39m,
                            FName = "Soğan-1 adet",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 88,
                            Calori = 51m,
                            FName = "Soya filizi-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 89,
                            Calori = 30m,
                            FName = "Şalgam-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 90,
                            Calori = 118m,
                            FName = "Taze biberiye-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 91,
                            Calori = 32m,
                            FName = "Taze fasülye-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 92,
                            Calori = 30m,
                            FName = "Taze fesleğen-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 93,
                            Calori = 101m,
                            FName = "Taze kekik-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 94,
                            Calori = 33m,
                            FName = "Taze kişniş-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 95,
                            Calori = 65m,
                            FName = "Taze nane-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 96,
                            Calori = 255m,
                            FName = "Taze tarhun-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 97,
                            Calori = 80m,
                            FName = "Taze zencefil-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 98,
                            Calori = 33m,
                            FName = "Tere-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 99,
                            Calori = 19m,
                            FName = "Turp-1 adet",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 100,
                            Calori = 75m,
                            FName = "Yer elması-1 adet",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 101,
                            Calori = 49m,
                            FName = "Yonca filizi-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 102,
                            Calori = 31m,
                            FName = "Defne yaprağı-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 103,
                            Calori = 26m,
                            FName = "Karabiber-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 104,
                            Calori = 32m,
                            FName = "Karanfil-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 105,
                            Calori = 35m,
                            FName = "Kereviz tozu-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 106,
                            Calori = 16m,
                            FName = "Kırmızı pulbiber-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 107,
                            Calori = 13m,
                            FName = "Kimyon-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 108,
                            Calori = 15m,
                            FName = "Köri-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 109,
                            Calori = 27m,
                            FName = "Kuru bamya-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 110,
                            Calori = 30m,
                            FName = "Kuru biberiye-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 111,
                            Calori = 25m,
                            FName = "Kuru dereotu-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 112,
                            Calori = 26m,
                            FName = "Kuru domates-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 113,
                            Calori = 27m,
                            FName = "Kuru fesleğen-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 114,
                            Calori = 28m,
                            FName = "Kuru kekik-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 115,
                            Calori = 30m,
                            FName = "Kuru kişniş-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 116,
                            Calori = 28m,
                            FName = "Kuru maydonoz-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 117,
                            Calori = 25m,
                            FName = "Kuru nane-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 118,
                            Calori = 29m,
                            FName = "Kuru patlıcan-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 119,
                            Calori = 26m,
                            FName = "Kuru tarhun-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 120,
                            Calori = 14m,
                            FName = "Lavanta-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 121,
                            Calori = 14m,
                            FName = "Mahlep-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 122,
                            Calori = 19m,
                            FName = "Muskat-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 123,
                            Calori = 35m,
                            FName = "Rezene tohumu-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 124,
                            Calori = 16m,
                            FName = "Safran-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 125,
                            Calori = 15m,
                            FName = "Sarımsak tozu-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 126,
                            Calori = 19m,
                            FName = "Sumak-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 127,
                            Calori = 19m,
                            FName = "Tarçın-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 128,
                            Calori = 12m,
                            FName = "Vanilya-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 129,
                            Calori = 16m,
                            FName = "Yenibahar-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 130,
                            Calori = 35m,
                            FName = "Zencefil tozu-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 131,
                            Calori = 14m,
                            FName = "Zerdeçal-100 gram",
                            FoodTypeId = 2
                        },
                        new
                        {
                            Id = 132,
                            Calori = 127m,
                            FName = "Akıtma-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 133,
                            Calori = 503m,
                            FName = "Anne kurabiyesi-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 134,
                            Calori = 426m,
                            FName = "Avcı böreği-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 135,
                            Calori = 431m,
                            FName = "Boşnak mantısı-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 136,
                            Calori = 208m,
                            FName = "Çekirdekli ekmek-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 137,
                            Calori = 528m,
                            FName = "Çiğ börek-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 138,
                            Calori = 192m,
                            FName = "Ekşi mayalı köy ekmeği-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 139,
                            Calori = 441m,
                            FName = "Elmalı turta-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 140,
                            Calori = 327m,
                            FName = "Ev yapımı lahmacun-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 141,
                            Calori = 233m,
                            FName = "Fındık lahmacun-1 porsiyon",
                            FoodTypeId = 3
                        },
                        new
                        {
                            Id = 142,
                            Calori = 378m,
                            FName = "Akdarı-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 143,
                            Calori = 354m,
                            FName = "Arpa-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 144,
                            Calori = 584m,
                            FName = "Ayçiçeği tohumu-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 145,
                            Calori = 216m,
                            FName = "Buğday kepeği-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 146,
                            Calori = 281m,
                            FName = "Çavdar tohumu-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 147,
                            Calori = 388m,
                            FName = "Esmer pirinç-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 148,
                            Calori = 390m,
                            FName = "Galeta-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 149,
                            Calori = 399m,
                            FName = "Grissini (İnce)-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 150,
                            Calori = 351m,
                            FName = "İnce mısır unu-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 151,
                            Calori = 343m,
                            FName = "Kara buğday-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 152,
                            Calori = 534m,
                            FName = "Keten tohumu-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 153,
                            Calori = 381m,
                            FName = "Mısır nişastası-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 154,
                            Calori = 237m,
                            FName = "Tortilla-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 155,
                            Calori = 246m,
                            FName = "Yulaf kepeği-100 gram",
                            FoodTypeId = 4
                        },
                        new
                        {
                            Id = 156,
                            Calori = 612m,
                            FName = "Akceviz-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 157,
                            Calori = 84m,
                            FName = "Bakla-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 158,
                            Calori = 27m,
                            FName = "Bambu filizi-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 159,
                            Calori = 33m,
                            FName = "Bamya-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 160,
                            Calori = 336m,
                            FName = "Beyaz fasülye-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 161,
                            Calori = 81m,
                            FName = "Bezelye-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 162,
                            Calori = 347m,
                            FName = "Barbunya fasülyesi-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 163,
                            Calori = 115m,
                            FName = "Börülce-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 164,
                            Calori = 353m,
                            FName = "Kahverengi mercimek-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 165,
                            Calori = 329m,
                            FName = "Kırmızı mercimek-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 166,
                            Calori = 12m,
                            FName = "Maş fasülyesi-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 167,
                            Calori = 364m,
                            FName = "Nohut-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 168,
                            Calori = 147m,
                            FName = "Soya fasülyesi-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 169,
                            Calori = 567m,
                            FName = "Yer fıstığı-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 170,
                            Calori = 31m,
                            FName = "Yeşil fasülye-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 171,
                            Calori = 257m,
                            FName = "Yeşil mercimek-100 gram",
                            FoodTypeId = 5
                        },
                        new
                        {
                            Id = 172,
                            Calori = 208m,
                            FName = "Hindi but-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 173,
                            Calori = 100m,
                            FName = "Hindi füme-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 174,
                            Calori = 162m,
                            FName = "Hindi göğüs-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 175,
                            Calori = 121m,
                            FName = "Hindi jambon-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 176,
                            Calori = 165m,
                            FName = "Hindi kıyma-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 177,
                            Calori = 268m,
                            FName = "Hindi pastırma-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 178,
                            Calori = 221m,
                            FName = "Tavuk but-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 179,
                            Calori = 201m,
                            FName = "Tavuk füme-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 180,
                            Calori = 165m,
                            FName = "Tavuk göğüs-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 181,
                            Calori = 100m,
                            FName = "Tavuk jambon-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 182,
                            Calori = 177m,
                            FName = "Tavuk kalça şiş-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 183,
                            Calori = 143m,
                            FName = "Tavuk kıyma-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 184,
                            Calori = 124m,
                            FName = "Tavuk salam-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 185,
                            Calori = 168m,
                            FName = "Dana antrikot-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 186,
                            Calori = 185m,
                            FName = "Dana biftek-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 187,
                            Calori = 168m,
                            FName = "Dana bonfile-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 188,
                            Calori = 125m,
                            FName = "Dana dil-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 189,
                            Calori = 181m,
                            FName = "Dana jambon-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 190,
                            Calori = 155m,
                            FName = "Dana kıyma-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 191,
                            Calori = 188m,
                            FName = "Dana pirzola-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 192,
                            Calori = 445m,
                            FName = "Dana salam-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 193,
                            Calori = 320m,
                            FName = "Dana sosis-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 194,
                            Calori = 445m,
                            FName = "Dana sucuk-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 195,
                            Calori = 231m,
                            FName = "Kuzu but-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 196,
                            Calori = 376m,
                            FName = "Kuzu incik-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 197,
                            Calori = 244m,
                            FName = "Kuzu kıyma-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 198,
                            Calori = 231m,
                            FName = "Kuzu kol-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 199,
                            Calori = 343m,
                            FName = "Kuzu pirzola-100 gram",
                            FoodTypeId = 6
                        },
                        new
                        {
                            Id = 200,
                            Calori = 118m,
                            FName = "Barbun-70 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 201,
                            Calori = 112m,
                            FName = "Çinekop-60 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 202,
                            Calori = 360m,
                            FName = "Çipura-300 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 203,
                            Calori = 100m,
                            FName = "Fener balığı-100 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 204,
                            Calori = 42m,
                            FName = "İstavrit-25 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 205,
                            Calori = 45m,
                            FName = "Hamsi-20 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 206,
                            Calori = 188m,
                            FName = "Kalamar-250 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 207,
                            Calori = 8m,
                            FName = "Karides-8 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 208,
                            Calori = 164m,
                            FName = "Kılıç balığı-100 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 209,
                            Calori = 279m,
                            FName = "Levrek-300 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 210,
                            Calori = 336m,
                            FName = "Lüfer-200 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 211,
                            Calori = 180m,
                            FName = "Mezgit-200 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 212,
                            Calori = 336m,
                            FName = "Palamut-200 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 213,
                            Calori = 183m,
                            FName = "Somon-100 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 214,
                            Calori = 184m,
                            FName = "Ton balığı-100 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 215,
                            Calori = 318m,
                            FName = "Uskumru-200 gram",
                            FoodTypeId = 7
                        },
                        new
                        {
                            Id = 216,
                            Calori = 68m,
                            FName = "Keçi sütü-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 217,
                            Calori = 108m,
                            FName = "Koyun sütü-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 218,
                            Calori = 35m,
                            FName = "Normal light süt-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 219,
                            Calori = 61m,
                            FName = "Normal yağlı süt-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 220,
                            Calori = 62m,
                            FName = "Laktozsuz süt-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 221,
                            Calori = 41m,
                            FName = "Light kefir-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 222,
                            Calori = 57m,
                            FName = "Light yoğurt-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 223,
                            Calori = 65m,
                            FName = "Tam yağlı kefir-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 224,
                            Calori = 84m,
                            FName = "Yağlı yoğurt-100 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 225,
                            Calori = 101m,
                            FName = "Çedar peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 226,
                            Calori = 95m,
                            FName = "Çökelek peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 227,
                            Calori = 59m,
                            FName = "Eski kaşar peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 228,
                            Calori = 78m,
                            FName = "Ezine keçi peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 229,
                            Calori = 89m,
                            FName = "Gravyer peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 230,
                            Calori = 45m,
                            FName = "Light beyaz peynir-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 231,
                            Calori = 45m,
                            FName = "Light dil peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 232,
                            Calori = 36m,
                            FName = "Light labne-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 233,
                            Calori = 56m,
                            FName = "Light taze kaşar peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 234,
                            Calori = 21m,
                            FName = "Lor peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 235,
                            Calori = 110m,
                            FName = "Krem peynir-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 236,
                            Calori = 70m,
                            FName = "Mozzerella-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 237,
                            Calori = 59m,
                            FName = "Normal beyaz peynir-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 238,
                            Calori = 52m,
                            FName = "Normal labne-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 239,
                            Calori = 45m,
                            FName = "Normal dil peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 240,
                            Calori = 82m,
                            FName = "Otlu peynir-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 241,
                            Calori = 95m,
                            FName = "Parmesan peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 242,
                            Calori = 21m,
                            FName = "Ricotta peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 243,
                            Calori = 92m,
                            FName = "Rokfor peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 244,
                            Calori = 59m,
                            FName = "Saf keçi peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 245,
                            Calori = 101m,
                            FName = "Taze kaşar peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 246,
                            Calori = 89m,
                            FName = "Tulum peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 247,
                            Calori = 71m,
                            FName = "Yörük peyniri-25 gram",
                            FoodTypeId = 8
                        },
                        new
                        {
                            Id = 248,
                            Calori = 1m,
                            FName = "Bıldırcın yumurtası-1 adet",
                            FoodTypeId = 16
                        },
                        new
                        {
                            Id = 249,
                            Calori = 79m,
                            FName = "Yumurta-1 adet",
                            FoodTypeId = 16
                        },
                        new
                        {
                            Id = 250,
                            Calori = 15m,
                            FName = "Yumurta akı-1 adet",
                            FoodTypeId = 16
                        },
                        new
                        {
                            Id = 251,
                            Calori = 66m,
                            FName = "Yumurta sarısı-1 adet",
                            FoodTypeId = 16
                        },
                        new
                        {
                            Id = 252,
                            Calori = 590m,
                            FName = "Antep fıstığı-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 253,
                            Calori = 560m,
                            FName = "Ay çekirdeği-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 254,
                            Calori = 600m,
                            FName = "Badem-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 255,
                            Calori = 650m,
                            FName = "Ceviz-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 256,
                            Calori = 640m,
                            FName = "Çam fıstığı-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 257,
                            Calori = 630m,
                            FName = "Fındık-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 258,
                            Calori = 610m,
                            FName = "Kabak çekirdeği-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 259,
                            Calori = 610m,
                            FName = "Kaju fıstığı-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 260,
                            Calori = 580m,
                            FName = "Yer fıstığı-100 gram",
                            FoodTypeId = 9
                        },
                        new
                        {
                            Id = 261,
                            Calori = 34m,
                            FName = "Anason tohumu-10 gram",
                            FoodTypeId = 10
                        },
                        new
                        {
                            Id = 262,
                            Calori = 20m,
                            FName = "Çörek otu-10 gram",
                            FoodTypeId = 10
                        },
                        new
                        {
                            Id = 263,
                            Calori = 53m,
                            FName = "Haşhaş tohumu-10 gram",
                            FoodTypeId = 10
                        },
                        new
                        {
                            Id = 264,
                            Calori = 46m,
                            FName = "Keten tohumu-10 gram",
                            FoodTypeId = 10
                        },
                        new
                        {
                            Id = 265,
                            Calori = 44m,
                            FName = "Ayçiçek yağı-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 266,
                            Calori = 44m,
                            FName = "Canola yağı-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 267,
                            Calori = 44m,
                            FName = "Fındık yağı-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 268,
                            Calori = 44m,
                            FName = "Margarin-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 269,
                            Calori = 44m,
                            FName = "Soya yağı-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 270,
                            Calori = 44m,
                            FName = "Susam yağı-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 271,
                            Calori = 44m,
                            FName = "Tereyağı-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 272,
                            Calori = 44m,
                            FName = "Zeytinyağı-1 tatlı kaşığı",
                            FoodTypeId = 11
                        },
                        new
                        {
                            Id = 273,
                            Calori = 1m,
                            FName = "Balzemik sirke-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 274,
                            Calori = 5m,
                            FName = "Elma sirkesi-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 275,
                            Calori = 7m,
                            FName = "Hardal-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 276,
                            Calori = 11m,
                            FName = "Ketçap-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 277,
                            Calori = 37m,
                            FName = "Mayonez light-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 278,
                            Calori = 8m,
                            FName = "Nar ekşisi sosu-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 279,
                            Calori = 52m,
                            FName = "Pesto sos-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 280,
                            Calori = 1m,
                            FName = "Pirinç sirkesi-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 281,
                            Calori = 7m,
                            FName = "Soya sosu-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 282,
                            Calori = 1m,
                            FName = "Üzüm sirkesi-10 gram",
                            FoodTypeId = 12
                        },
                        new
                        {
                            Id = 283,
                            Calori = 30m,
                            FName = "Bamya turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 284,
                            Calori = 14m,
                            FName = "Biber turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 285,
                            Calori = 10m,
                            FName = "Domates turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 286,
                            Calori = 30m,
                            FName = "Fasülye turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 287,
                            Calori = 24m,
                            FName = "Havuç turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 288,
                            Calori = 24m,
                            FName = "Karnıbahar turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 289,
                            Calori = 30m,
                            FName = "Kereviz turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 290,
                            Calori = 10m,
                            FName = "Kuru soğan turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 291,
                            Calori = 10m,
                            FName = "Lahana turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 292,
                            Calori = 10m,
                            FName = "Pancar turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 293,
                            Calori = 10m,
                            FName = "Patlıcan turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 294,
                            Calori = 6m,
                            FName = "Salatalık turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 295,
                            Calori = 10m,
                            FName = "Taze soğan turşusu-100 gram",
                            FoodTypeId = 13
                        },
                        new
                        {
                            Id = 296,
                            Calori = 270m,
                            FName = "Ahududu reçeli-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 297,
                            Calori = 320m,
                            FName = "Bal-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 298,
                            Calori = 390m,
                            FName = "Beyaz şeker-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 299,
                            Calori = 270m,
                            FName = "Böğürtlen reçeli-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 300,
                            Calori = 270m,
                            FName = "Çilek reçeli-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 301,
                            Calori = 290m,
                            FName = "Dut pekmezi-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 302,
                            Calori = 500m,
                            FName = "Esmer şeker-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 303,
                            Calori = 620m,
                            FName = "Jöle-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 304,
                            Calori = 270m,
                            FName = "İncir reçeli-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 305,
                            Calori = 400m,
                            FName = "Kakao-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 306,
                            Calori = 270m,
                            FName = "Kayısı reçeli-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 307,
                            Calori = 290m,
                            FName = "Keçiboynuzu pekmezi-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 308,
                            Calori = 390m,
                            FName = "Pudra şekeri-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 309,
                            Calori = 260m,
                            FName = "Şekersiz kızılcık reçeli-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 310,
                            Calori = 68m,
                            FName = "Şeftali kompostosu-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 311,
                            Calori = 290m,
                            FName = "Üzüm pekmezi-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 312,
                            Calori = 250m,
                            FName = "Yaş pasta-100 gram",
                            FoodTypeId = 14
                        },
                        new
                        {
                            Id = 313,
                            Calori = 194m,
                            FName = "Albeni-1 adet",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 314,
                            Calori = 594m,
                            FName = "Biskrem-1 paket (120 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 315,
                            Calori = 1163m,
                            FName = "Burger whopper menü-1 menü",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 316,
                            Calori = 124m,
                            FName = "Doritos nacho-1 paket (25 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 317,
                            Calori = 231m,
                            FName = "Eti canga-1 adet",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 318,
                            Calori = 289m,
                            FName = "Köfteci Yusuf Köfte-100 gram",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 319,
                            Calori = 548m,
                            FName = "Lays-100 gram",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 320,
                            Calori = 248m,
                            FName = "Magnum Antep fıstıklı-1 adet (75 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 321,
                            Calori = 251m,
                            FName = "Magnum bademli-1 adet (76 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 322,
                            Calori = 247m,
                            FName = "Magnum double çikolata-1 adet (72,5 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 323,
                            Calori = 239m,
                            FName = "Magnum classic-1 adet (77 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 324,
                            Calori = 250m,
                            FName = "Magnum tiramisu-1 adet (82 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 325,
                            Calori = 900m,
                            FName = "Mc donald’s chicken menü-1 menü",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 326,
                            Calori = 251m,
                            FName = "Pop kek-1 adet",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 327,
                            Calori = 861m,
                            FName = "Pringles-1 kutu",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 328,
                            Calori = 404m,
                            FName = "Sade mısır cipsi-1 paket (orta)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 329,
                            Calori = 1174m,
                            FName = "Tavuk dünyası bi’köri-1 porsiyon",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 330,
                            Calori = 184m,
                            FName = "Toblerone-1 paket (35 gr,)",
                            FoodTypeId = 15
                        },
                        new
                        {
                            Id = 331,
                            Calori = 507m,
                            FName = "Eti tutku bisküvi-1 paket",
                            FoodTypeId = 15
                        });
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.FoodMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<decimal>("Portion")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("FoodMeals");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FoodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Meyve"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sebze/Baharat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hamur İşi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tahıl"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Baklagil"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Et"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Deniz Ürünleri"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Süt Ürünleri"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kuruyemiş"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tohumlar"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Yağ"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Soslar"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Turşular"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Tatlılar"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Fastfood & Atıştırmalık"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Yumurtalar"
                        });
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.MealType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MTName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MealTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MTName = "Kahvaltı"
                        },
                        new
                        {
                            Id = 2,
                            MTName = "Öğle Yemeği"
                        },
                        new
                        {
                            Id = 3,
                            MTName = "Aşkam Yemeği"
                        },
                        new
                        {
                            Id = 4,
                            MTName = "Ara Öğün"
                        });
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.Food", b =>
                {
                    b.HasOne("BA.DietTrackApp.Entity.Entities.FoodType", "FoodType")
                        .WithMany("Foods")
                        .HasForeignKey("FoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodType");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.FoodMeal", b =>
                {
                    b.HasOne("BA.DietTrackApp.Entity.Entities.Food", "Food")
                        .WithMany("FoodMeals")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BA.DietTrackApp.Entity.Entities.Meal", "Meal")
                        .WithMany("FoodMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.Meal", b =>
                {
                    b.HasOne("BA.DietTrackApp.Entity.Entities.MealType", "MealType")
                        .WithMany("Meals")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BA.DietTrackApp.Entity.Entities.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.Food", b =>
                {
                    b.Navigation("FoodMeals");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.FoodType", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.Meal", b =>
                {
                    b.Navigation("FoodMeals");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.MealType", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("BA.DietTrackApp.Entity.Entities.User", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
